logger:
  # This logger will output a txt file in tum style
  enable_pose_logger: true
  pose_log_file: "/home/freir/MobRobFinalProj/drift/ros_Logs/test30.txt"
  vel_log_file: "/home/freir/MobRobFinalProj/drift/ros_Logs/test_velocity30.txt"
  pose_log_rate: 100 # Hz
state:
  rotation_std_value: 0.1
  velocity_std_value: 0.1
  position_std_value: 0.1
